Please review Monsters
NamidaSai/BabyRogue pull request #4
Opened 2020-10-29 23:49 UTC by akshaykgarg

2020-10-30 10:00 UTC, NamidaSai requested changes
Comments for "designer-side" improvements even though the current code makes sense on programmer side. Can wait for next push. 

Only thing required before merging: the rest of the codebase is passing in a char to the Monster.cpp constructor not a string.

2020-10-30 10:06 UTC, NamidaSai commented
One more thought: we will actually be using the full name type to display event messages in the player log. "You attacked a Troll!" etc. So yeah, need the full name back from programmer side as well not only for being nice to theoretical designers.

2020-11-03 12:48 UTC, akshaykgarg commented on output/Data/monsters.json
> +    "T":{
The json format has been this way now

2020-11-03 15:41 UTC, NamidaSai approved these changes
Good to merge

2020-11-03 21:47 UTC, merged